spring:
  config:
    activate:
      on-profile: "prod"
build:
  version: "1.0"
accounts:
  message: "Welcome to EazyBank accounts related Prod1 APIs "
  contactDetails:
    name: "Johnny Prod1"
    email: "john@Prod1.com"
  onCallSupport:
    - (555) 555-1235
    - (555) 523-1345
