server:
  port: 8082
spring:
  config:
    import:
      - accounts-qa.yml
      - accounts-prod.yml
  profiles:
    active: "qa"
  application:
    name: 'ACCOUNTS_MS'
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    #database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
build:
  version: "3.0"
accounts:
  message: "Welcome to EazyBank accounts related localeee APIs "
  contactDetails:
    name: "John Doe - Default"
    email: "{cipher}801205b32641e21fa42800f14baee03263fe4c608e90ac6a567d1d6b47c33f1b9a256a44429f9270bd7d9087dd0ba350"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
