spring:
  config:
    activate:
      on-profile: "prod"
build:
  version: "1.0"
accounts:
  message: "Welcome to EazyBank accounts related Production APIs "
  contactDetails:
    name: "Johnny Production"
    email: "john@Production.com"
  onCallSupport:
    - (555) 555-1235
    - (555) 523-1345
